# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-20 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='correct_choice',
            field=models.BooleanField(default=False),
        ),
    ]
