# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0002_auto_20160705_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='card_number',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='keyb_number',
            field=models.DecimalField(decimal_places=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='codes',
            name='valid_from',
            field=models.DateTimeField(null=True, verbose_name='valid from'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='valid_to',
            field=models.DateTimeField(null=True, verbose_name='valid to'),
        ),
    ]
