# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0004_auto_20160705_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='type',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
