# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-05 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0005_auto_20160705_1746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Codes',
            new_name='Code',
        ),
    ]
