# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-19 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0007_auto_20160705_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='keyb_number',
            field=models.CharField(blank=True, default=None, max_length=15, null=True),
        ),
    ]
