# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0009_auto_20160720_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='keyb_number',
            new_name='code_number',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='card_number',
            new_name='pin',
        ),
        migrations.AddField(
            model_name='code',
            name='created',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_type',
            field=models.CharField(blank=True, default='k', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='code',
            unique_together=set([('code_type', 'code_number')]),
        ),
    ]
