# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-27 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0011_auto_20160727_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='comment',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='code_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True),
        ),
    ]
