# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesscodes', '0012_auto_20160727_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='code_type',
            field=models.CharField(blank=True, default='', max_length=3, null=True),
        ),
    ]
